"""Type stubs for the C++ chess engine extension (pybind11)."""

from __future__ import annotations

from collections.abc import Sequence

# ── Enums ────────────────────────────────────────────────────────────

class Color:
    WHITE: Color
    BLACK: Color
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...
    def __bool__(self) -> bool: ...

class PieceType(int):
    PAWN: PieceType
    KNIGHT: PieceType
    BISHOP: PieceType
    ROOK: PieceType
    QUEEN: PieceType
    KING: PieceType
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class GameState:
    ONGOING: GameState
    CHECKMATE: GameState
    STALEMATE: GameState
    DRAW_BY_FIFTY_MOVE: GameState
    DRAW_BY_INSUFFICIENT_MATERIAL: GameState
    DRAW_BY_REPETITION: GameState
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

# ── Enum-level constants ─────────────────────────────────────────────

WHITE: Color
BLACK: Color
PAWN: PieceType
KNIGHT: PieceType
BISHOP: PieceType
ROOK: PieceType
QUEEN: PieceType
KING: PieceType
ONGOING: GameState
CHECKMATE: GameState
STALEMATE: GameState
DRAW_BY_FIFTY_MOVE: GameState
DRAW_BY_INSUFFICIENT_MATERIAL: GameState
DRAW_BY_REPETITION: GameState

SQUARES: list[int]

# ── Types ────────────────────────────────────────────────────────────

class Piece:
    @property
    def color(self) -> Color: ...
    @property
    def piece_type(self) -> PieceType: ...
    @property
    def type(self) -> PieceType: ...
    def symbol(self) -> str: ...

class Move:
    from_square: int
    to_square: int
    promotion: int
    def uci(self) -> str: ...
    @staticmethod
    def from_uci(uci: str) -> Move: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

class Board:
    def __init__(self, fen: str = ...) -> None: ...
    @property
    def turn(self) -> bool: ...
    @property
    def legal_moves(self) -> list[Move]: ...
    def fen(self) -> str: ...
    def to_fen(self) -> str: ...
    def set_fen(self, fen: str) -> None: ...
    @staticmethod
    def from_fen(fen: str) -> Board: ...
    def copy(self) -> Board: ...
    def push(self, move: Move) -> None: ...
    def push_san(self, san: str) -> None: ...
    def push_null(self) -> None: ...
    def pop(self) -> Move: ...
    def make_move(self, move: Move) -> None: ...
    def generate_legal_moves(self) -> list[Move]: ...
    def is_game_over(self) -> GameState: ...
    def is_check(self) -> bool: ...
    def is_capture(self, move: Move) -> bool: ...
    def is_castling(self, move: Move) -> bool: ...
    def is_en_passant(self, move: Move) -> bool: ...
    def is_kingside_castling(self, move: Move) -> bool: ...
    def is_queenside_castling(self, move: Move) -> bool: ...
    def piece_at(self, square: int) -> Piece | None: ...
    def pieces(self, piece_type: PieceType, color: Color) -> list[int]: ...
    def king(self, color: Color) -> int: ...
    def get_side_to_move(self) -> bool: ...
    def get_en_passant_square(self) -> int: ...
    def get_halfmove_clock(self) -> int: ...
    def get_fullmove_number(self) -> int: ...
    def get_castling_rights(self) -> int: ...
    def has_kingside_castling_rights(self, color: Color) -> bool: ...
    def has_queenside_castling_rights(self, color: Color) -> bool: ...
    def get_piece_bb(self, piece_type: PieceType, color: Color) -> int: ...
    def get_color_bb(self, color: Color) -> int: ...
    def get_all_pieces_bb(self) -> int: ...
    def perft(self, depth: int) -> int: ...
    def pretty(self) -> str: ...

# ── Transposition Table ─────────────────────────────────────────────

class BoundType:
    EXACT: BoundType
    LOWER: BoundType
    UPPER: BoundType
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class TTEntry:
    key: int
    score: int
    best_move: Move
    depth: int
    bound: int
    age: int
    def __repr__(self) -> str: ...

class TranspositionTable:
    def __init__(self, size_mb: int = 64) -> None: ...
    def resize(self, size_mb: int) -> None: ...
    def clear(self) -> None: ...
    def increment_age(self) -> None: ...
    def probe(self, key: int) -> TTEntry | None: ...
    def try_get_score(
        self, entry: TTEntry, depth: int, alpha: int, beta: int
    ) -> int | None: ...
    def store(
        self,
        key: int,
        depth: int,
        score: int,
        best_move: Move | None,
        bound: BoundType,
    ) -> None: ...
    def size(self) -> int: ...
    def capacity(self) -> int: ...
    def hashfull(self) -> int: ...
    def current_age(self) -> int: ...

class Zobrist:
    def __init__(self) -> None: ...
    def hash_board(self, board: Board) -> int: ...
    def make_move_hash(self, board: Board, move: Move) -> int: ...
    def make_null_move_hash(self, board: Board) -> int: ...
    def get_current_hash(self) -> int: ...
    def set_current_hash(self, hash_val: int) -> None: ...
    def invalidate_hash(self) -> None: ...

# ── SearchConfig ──────────────────────────────────────────────────────

class SearchConfig:
    # Move ordering
    use_move_ordering: bool
    use_mvv_lva: bool
    use_history_heuristic: bool
    use_countermove_heuristic: bool
    use_see_ordering: bool
    use_killer_moves: bool
    use_hash_move_ordering: bool
    history_max_score: int
    killer_slots_per_ply: int
    see_capture_threshold: int
    # Search algorithms
    use_alpha_beta: bool
    use_pvs: bool
    use_quiescence_search: bool
    qs_max_depth: int
    use_iid: bool
    iid_min_depth: int
    iid_depth_reduction: int
    # Pruning
    use_null_move_pruning: bool
    nmp_reduction_r: int
    nmp_min_depth: int
    use_lmr: bool
    lmr_min_depth: int
    lmr_min_move_number: int
    use_futility_pruning: bool
    futility_margin_standard: int
    use_extended_futility_pruning: bool
    futility_margin_extended: int
    use_reverse_futility_pruning: bool
    rfp_margin_multiplier: int
    rfp_max_depth: int
    use_delta_pruning: bool
    delta_margin: int
    use_see_pruning_in_qs: bool
    # State & hashing
    use_aspiration_windows: bool
    aspiration_window_margin: int
    use_check_extensions: bool
    max_check_extensions: int
    use_transposition_table: bool
    tt_size_mb: int
    use_tt_aging: bool
    # Syzygy
    use_syzygy: bool
    use_50_move_rule: bool
    # Lazy SMP
    use_lazy_smp: bool
    smp_num_threads: int
    # Time
    max_time: float
    has_max_time: bool
    def __init__(self) -> None: ...

class SearchStats:
    nodes: int
    depth: int
    seldepth: int
    tt_hits: int
    hashfull: int
    beta_cutoffs: int
    first_move_cuts: int
    killer_cuts: int
    history_cuts: int
    qsearch_nodes: int
    null_move_cuts: int
    pvs_researches: int
    lmr_researches: int
    qs_see_pruning: int
    qs_delta_pruning: int
    check_extensions: int
    iid_searches: int
    root_move_changes: int
    history_saturation: float
    score: int
    best_move: Move
    def __repr__(self) -> str: ...

class Search:
    def __init__(
        self,
        board: Board,
        config: SearchConfig,
        evaluator: CppEvaluator,
        syzygy: CppSyzygyProber | None = None,
    ) -> None: ...
    def find_best_move(self, depth: int) -> tuple[int, Move]: ...
    def get_stats(self) -> SearchStats: ...
    def reset_state(
        self,
        clear_tt: bool = True,
        clear_history: bool = True,
        clear_killers: bool = True,
    ) -> None: ...

class MoveSorterConfig:
    use_move_ordering: bool
    use_mvv_lva: bool
    use_history_heuristic: bool
    use_countermove_heuristic: bool
    use_see_ordering: bool
    use_killer_moves: bool
    use_hash_move_ordering: bool
    history_max_score: int
    killer_slots_per_ply: int
    see_capture_threshold: int
    def __init__(self) -> None: ...

class MoveSorter:
    def __init__(self, config: MoveSorterConfig) -> None: ...
    def sort_moves(
        self,
        board: Board,
        moves: list[Move],
        ply: int,
        hash_move: Move | None,
        previous_move: Move | None,
    ) -> list[Move]: ...
    def sort_tactical(self, board: Board, moves: list[Move]) -> list[Move]: ...
    def see(self, board: Board, move: Move) -> int: ...
    def on_beta_cutoff(
        self,
        move: Move,
        ply: int,
        depth: int,
        previous_move: Move | None,
        is_tactical: bool,
    ) -> None: ...
    def history_saturation(self) -> float: ...
    def reset(self, clear_history: bool = True, clear_killers: bool = True) -> None: ...
    def get_killers(self, ply: int) -> list[Move]: ...
    def get_history(self, from_sq: int, to_sq: int, promo: int) -> int: ...
    def get_history_table(self) -> dict[tuple[int, int, int], int]: ...
    def get_killer_moves_dict(self) -> dict[int, list[Move]]: ...

# ── Evaluator ──────────────────────────────────────────────────────

class EvalConfig:
    use_pst: bool
    use_pawn_structure: bool
    use_mobility: bool
    use_king_safety: bool
    game_stage_conscious: bool
    def __init__(self) -> None: ...

class CppEvaluator:
    def __init__(self, config: EvalConfig) -> None: ...
    def go(self, board: Board) -> int: ...

# ── Syzygy ─────────────────────────────────────────────────────────

class CppSyzygyProber:
    def __init__(
        self,
        path: str,
        use_50_move_rule: bool,
        wdl_func: object,
        dtz_func: object,
    ) -> None: ...
    @staticmethod
    def piece_count(board: Board) -> int: ...
    def probe_wdl(self, board: Board) -> int | None: ...
    def probe_dtz(self, board: Board) -> int | None: ...

# ── Free functions ───────────────────────────────────────────────────

def compute_attacked_squares(board: Board, color: Color) -> int: ...
def get_attacked_squares(board: Board, color: Color) -> int: ...
def is_in_check(board: Board, color: Color) -> bool: ...
def move_to_uci(move: Move) -> str: ...
def move_to_string(move: Move, board: Board) -> str: ...
def move_debug_string(move: Move, board: Board) -> str: ...
def moves_to_string(moves: Sequence[Move], board: Board) -> str: ...
def square_file(square: int) -> int: ...
def square_rank(square: int) -> int: ...
