[project]
name = "engine"
version = "0.1.0"
description = ""
authors = [
    {name = "Ethan Perry",email = "86326912+wheres-perry@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "torch (>=2.7.0,<3.0.0)",
    "numpy (>=2.2.5,<3.0.0)",
    "python-chess (>=1.999,<2.0)"
]

[tool.poetry]
packages = [{include = "engine", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
