[project]
name = "ChessEngine"
version = "0.1.0"
description = ""
authors = [
    {name = "Ethan Perry",email = "86326912+wheres-perry@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.12"


[tool.poetry]
packages = [{include = "ChessEngine", from = "src"}]


[tool.poetry.dependencies]
torch = "^2.7.0"
numpy = "^2.2.5"
python-chess = "^1.999"
pytest = "^8.3.5"
[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
