FROM mcr.microsoft.com/devcontainers/python:3.11

# Install system dependencies, adding ccache
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    ccache \
    curl \
    git \
    stockfish \
    dos2unix \
    sudo \
    && rm -rf /var/lib/apt/lists/*


RUN curl -LsSf https://astral.sh/uv/install.sh | sh \
    && mv /root/.local/bin/uv /usr/local/bin/uv \
    && mv /root/.local/bin/uvx /usr/local/bin/uvx \
    && rm -rf /root/.local/bin/env* /root/.cargo /root/.uv

# User creation
ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN if ! getent group $USER_GID >/dev/null 2>&1; then \
    groupadd --gid $USER_GID $USERNAME; \
    fi \
    && if ! id -u $USERNAME >/dev/null 2>&1; then \
    useradd --uid $USER_UID --gid $USER_GID -m $USERNAME; \
    fi \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME


    
USER $USERNAME

# Create a .condarc file that disables auto activation of base environment
RUN echo "auto_activate_base: false" > ~/.condarc