FROM mcr.microsoft.com/devcontainers/python:3.11

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    curl \
    git \
    pipx \
    stockfish \
    dos2unix \
    && rm -rf /var/lib/apt/lists/*

# Install global Python tools
RUN pipx install poetry
RUN pipx install pre-commit
RUN pipx install ruff
RUN pipx install pylint
RUN pipx install mypy
RUN pipx ensurepath
ENV PATH="/root/.local/bin:$PATH"

# Install Docker CLI
RUN curl -fsSL https://get.docker.com | sh

# User creation
ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN if ! getent group $USER_GID >/dev/null 2>&1; then \
    groupadd --gid $USER_GID $USERNAME; \
    fi \
    && if ! id -u $USERNAME >/dev/null 2>&1; then \
    useradd --uid $USER_UID --gid $USER_GID -m $USERNAME; \
    fi \
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

RUN usermod -aG docker $USERNAME

USER $USERNAME

# Create a .condarc file that disables auto activation of base environment
RUN echo "auto_activate_base: false" > ~/.condarc